Repository trifectatechfoundation/sudo-rs, pull requests merged in 2024-11, with the labels that each got.

#900 Implement a bunch of FreeBSD things
  src/pam/mod.rs
  src/sudo/mod.rs
  src/system/mod.rs
  src/system/term/user_term.rs
  src/system/time.rs
Labels: freebsd

#905 Second batch of FreeBSD changes for the compliance test suite
  README.md
  test-framework/e2e-tests/src/pty.rs
  test-framework/e2e-tests/src/su/flag_pty.rs
  test-framework/sudo-compliance-tests/src/lib.rs
  test-framework/sudo-compliance-tests/src/su.rs
  test-framework/sudo-compliance-tests/src/sudo/child_process/signal_handling/mod.rs
  test-framework/sudo-compliance-tests/src/sudo/child_process/signal_handling/print-sizes.sh
  test-framework/sudo-compliance-tests/src/sudo/env_reset.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list/credential_caching.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_non_interactive.rs
  test-framework/sudo-compliance-tests/src/sudo/sudo_ps1.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/timestamp_timeout.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/user_list.rs
  test-framework/sudo-compliance-tests/src/sudo/timestamp.rs
  test-framework/sudo-compliance-tests/src/sudo/timestamp/remove.rs
  test-framework/sudo-compliance-tests/src/sudo/timestamp/reset.rs
  test-framework/sudo-compliance-tests/src/sudo/timestamp/validate.rs
  test-framework/sudo-compliance-tests/src/sudo/use_pty.rs
  test-framework/sudo-test/src/ours.Dockerfile
Labels: freebsd

#904 First batch of FreeBSD changes for the compliance test suite
  test-framework/sudo-compliance-tests/src/snapshots/sudoers/cmnd/given_specific_command_then_other_command_is_not_allowed.snap
  test-framework/sudo-compliance-tests/src/snapshots/visudo/temporary_file_is_deleted_during_edition.snap
  test-framework/sudo-compliance-tests/src/su/flag_preserve_environment.rs
  test-framework/sudo-compliance-tests/src/su/flag_shell.rs
  test-framework/sudo-compliance-tests/src/su/pam.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_chdir.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list/long_format/mod.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list/nopasswd.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list/short_format/mod.rs
  test-framework/sudo-compliance-tests/src/sudo/nopasswd.rs
  test-framework/sudo-compliance-tests/src/sudo/passwd.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/host_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/include.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/run_as.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/user_list.rs
  test-framework/sudo-compliance-tests/src/sudo/syslog.rs
  test-framework/sudo-compliance-tests/src/visudo.rs
  test-framework/sudo-compliance-tests/src/visudo/flag_check.rs
  test-framework/sudo-compliance-tests/src/visudo/flag_file.rs
  test-framework/sudo-compliance-tests/src/visudo/flag_no_includes.rs
  test-framework/sudo-compliance-tests/src/visudo/flag_owner.rs
  test-framework/sudo-compliance-tests/src/visudo/include.rs
  test-framework/sudo-test/src/constants.rs
  test-framework/sudo-test/src/lib.rs
Labels: freebsd

#906 Make it run on FreeBSD
  src/su/mod.rs
  src/sudo/mod.rs
  src/sudo/pam.rs
  src/system/kernel.rs
  test-framework/sudo-compliance-tests/src/sudo/pam.rs
Labels: freebsd

#908 Support running the compliance test suite on FreeBSD
  test-framework/sudo-test/src/docker.rs
  test-framework/sudo-test/src/lib.rs
  test-framework/sudo-test/src/ours.freebsd.Dockerfile
  test-framework/sudo-test/src/ours.freebsd.Dockerfile.dockerignore
  test-framework/sudo-test/src/ours.linux.Dockerfile
  test-framework/sudo-test/src/ours.linux.Dockerfile.dockerignore
  test-framework/sudo-test/src/theirs.freebsd.Dockerfile
  test-framework/sudo-test/src/theirs.linux.Dockerfile
Labels: freebsd

#862 Add more Rustified version of kernel_check
  src/common/error.rs
  src/sudo/mod.rs
  src/system/kernel.rs
Labels: minor

#913 Add regression test for the IO safety violation
  test-framework/e2e-tests/src/regression.rs
Labels: minor

#916 clean up error type: 'authentication failed' was a misnomer
  src/common/error.rs
  src/sudo/pam.rs
  src/sudo/pipeline.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_group.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_non_interactive.rs
  test-framework/sudo-compliance-tests/src/sudo/nopasswd.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/host_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/host_list.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/run_as.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/runas_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/user_list.rs
Labels: minor

#919 rewrite arg0_passed tests
  test-framework/sudo-compliance-tests/src/sudo/path_search.rs
Labels: minor

#920 Add some modifications to CI recommended by SSF
  .github/dependabot.yml
  .github/workflows/ci.yaml
Labels: minor, CI
