Repository trifectatechfoundation/sudo-rs, pull requests merged in 2024-10, with the labels that each got.

#873 Couple more CI improvements
  .github/problem-matchers/rust.json
  .github/workflows/ci.yaml
Labels: CI

#876 Fix various assumptions in tests about how things are done on Linux
  src/common/context.rs
  src/common/resolve.rs
  src/system/audit.rs
  src/system/interface.rs
  src/system/mod.rs
Labels: freebsd

#882 Automate regeneration of PAM bindings
  .github/workflows/ci.yaml
  Makefile
  src/pam/converse.rs
  src/pam/error.rs
  src/pam/mod.rs
  src/pam/sys.rs
Labels: freebsd

#884 Handle a couple of portability issues affecting all non-Linux systems
  src/system/signal/set.rs
  src/system/term/user_term.rs
  src/system/wait.rs
Labels: freebsd

#887 Couple of small changes
  .github/workflows/ci.yaml
  src/su/mod.rs
  src/sudo/mod.rs
  src/system/mod.rs
  src/visudo/mod.rs
Labels: minor

#890 Fix breakage introduced by #887
  src/system/mod.rs
Labels: security

#891 Fix papercut in unit test
  src/system/mod.rs
Labels: minor

#896 Add more rowhammer prevention
  src/sudoers/ast.rs
  src/sudoers/tokens.rs
Labels: minor

#898 limit type conversion to SudoDefault to the DSL module
  src/defaults/settings_dsl.rs
Labels: minor
