Repository trifectatechfoundation/sudo-rs, pull requests merged in 2024-12, with the labels that each got.

#922 Fifth batch of FreeBSD changes for the compliance test suite
  test-framework/sudo-compliance-tests/src/su/flag_shell.rs
  test-framework/sudo-compliance-tests/src/su/limits.rs
  test-framework/sudo-compliance-tests/src/sudo/child_process/signal_handling/mod.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_login.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_shell.rs
  test-framework/sudo-compliance-tests/src/sudo/pam/env.rs
  test-framework/sudo-compliance-tests/src/sudo/path_search.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/secure_path.rs
  test-framework/sudo-test/src/constants.rs
Labels: freebsd

#935 Sixth batch of FreeBSD changes for the compliance test suite
  test-framework/sudo-compliance-tests/src/helpers.rs
  test-framework/sudo-compliance-tests/src/su/syslog.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_login.rs
  test-framework/sudo-compliance-tests/src/sudo/password_retry.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/run_as.rs
  test-framework/sudo-compliance-tests/src/sudo/syslog.rs
Labels: freebsd

#932 Add SETENV support
  src/sudo/env/environment.rs
  src/sudo/pipeline.rs
  src/sudo/pipeline/list.rs
  src/sudoers/ast.rs
  src/sudoers/mod.rs
  src/sudoers/policy.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/env/keep.rs
Labels: enhancement, C-parser, C-checker

#925 Treat conversation error as authentication failure
  src/sudo/pam.rs
Labels: C-pam, non-compliant, freebsd

#938 Revert "always give 'interaction is required' once if a conversation error occurred"
  src/sudo/pam.rs
Labels: freebsd
