Repository trifectatechfoundation/sudo-rs, pull requests merged in 2025-05, with the labels that each got.

#1085 Add apparmor profile enforcement
  Cargo.toml
  src/apparmor/mod.rs
  src/apparmor/sys.rs
  src/common/error.rs
  src/lib.rs
  src/sudo/env/environment.rs
  src/sudo/env/tests.rs
  src/sudo/pipeline.rs
  src/sudoers/ast.rs
  src/sudoers/policy.rs
  test-framework/sudo-compliance-tests/Cargo.toml
  test-framework/sudo-compliance-tests/src/sudo.rs
  test-framework/sudo-compliance-tests/src/sudo/apparmor.rs
  test-framework/sudo-test/Cargo.toml
  test-framework/sudo-test/src/docker.rs
  test-framework/sudo-test/src/ours.linux.Dockerfile
Labels: C-operatingsystem, ubuntu

#1100 AppArmor tests
  .github/workflows/ci.yaml
  src/common/error.rs
  test-framework/sudo-compliance-tests/src/sudo/apparmor.rs
  test-framework/sudo-test/src/docker.rs
  test-framework/sudo-test/src/lib.rs
Labels: CI, test-framework, ubuntu

#1073 Implement support for NOEXEC
  Cargo.toml
  src/common/context.rs
  src/defaults/mod.rs
  src/exec/mod.rs
  src/exec/no_pty.rs
  src/exec/noexec.rs
  src/exec/use_pty/parent.rs
  src/su/context.rs
  src/sudo/env/environment.rs
  src/sudo/env/tests.rs
  src/sudo/pipeline.rs
  src/sudoers/ast.rs
  src/sudoers/policy.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/noexec.rs
Labels: C-exec, linux, ubuntu

#1102 Update documentation
  docs/man/sudo.8.md
  docs/man/sudoers.5.md
Labels: documentation, minor

#1105 AppArmor finishing touches
  docs/man/sudoers.5.md
  src/defaults/mod.rs
  src/sudoers/policy.rs
Labels: documentation, C-parser, ubuntu

#1110 Release 0.2.6
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  docs/man/su.1.md
  docs/man/sudo.8.md
  docs/man/visudo.8.md
Labels: release

#1117 Fix error message for negating unknown settings
  src/sudoers/ast.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers.rs
Labels: C-parser

#1109 Fix spurious sigwinch_works_* failures with podman
  test-framework/sudo-compliance-tests/src/sudo/child_process/signal_handling/change-size.sh
  test-framework/sudo-compliance-tests/src/sudo/child_process/signal_handling/print-sizes.sh
Labels: minor, test-framework

#1108 add apparmor compliance test
  test-framework/sudo-compliance-tests/src/sudo/apparmor.rs
  test-framework/sudo-test/src/lib.rs
Labels: minor, test-framework

#1131 Also commit manpages to repository
  .gitignore
  docs/man/su.1.man
  docs/man/sudo.8.man
  docs/man/sudoers.5.man
  docs/man/visudo.8.man
  util/build-release.sh
  util/generate-docs.sh
Labels: documentation, minor, external-packaging

#1114 close_range improvements
  README.md
  src/common/error.rs
  src/exec/no_pty.rs
  src/exec/use_pty/monitor.rs
  src/exec/use_pty/parent.rs
  src/sudo/mod.rs
  src/system/kernel.rs
  src/system/mod.rs
  test-framework/sudo-test/src/docker/command.rs
Labels: ubuntu
