Repository trifectatechfoundation/sudo-rs, pull requests merged in 2025-07, with the labels that each got.

#1177 Test on alpine linux for musl
  .github/workflows/ci.yaml
Labels: minor, CI

#1173 Track two new CVE's of ogsudo
  docs/sudo-cve.md
Labels: documentation, minor

#1185 Fix the permission flags that visudo sets on the temporary file
  src/visudo/mod.rs
  test-framework/sudo-compliance-tests/src/visudo.rs
Labels: minor, C-visudo

#1202 FreeBSD fixes
  src/exec/mod.rs
  src/system/mod.rs
Labels: minor, portability, freebsd

#1221 Ignore test on Cirrus CI
  .cirrus.yml
Labels: freebsd

#1216 Sudoedit compliance tests (batch 2)
  src/sudo/pipeline/edit.rs
  src/system/audit.rs
  test-framework/sudo-compliance-tests/src/sudoedit.rs
  test-framework/sudo-compliance-tests/src/sudoedit/limits.rs
Labels: non-compliant, test-framework

#1220 Deduplicate FreeBSD sysctl handling and add safety comment
  src/system/mod.rs
Labels: C-operatingsystem, freebsd

#1188 Update CVE list with Sudoedit-related CVE's
  docs/sudo-cve.md
Labels: documentation

#1229 Add multi-arch checks in NOEXEC
  docs/man/sudoers.5.man
  docs/man/sudoers.5.md
  src/exec/noexec.rs
Labels: C-exec
