Repository trifectatechfoundation/sudo-rs, pull requests merged in 2025-03, with the labels that each got.

#1014 Use docker run --rm + docker kill instead of docker rm
  test-framework/sudo-test/src/docker.rs
Labels: test-framework

#1018 Couple of misc changes
  docs/man/su.1.md
  docs/man/sudo.8.md
  docs/man/visudo.8.md
  src/pam/securemem.rs
  src/sudo/pam.rs
  src/sudo/pipeline.rs
  util/generate-docs.sh
Labels: minor

#1023 Make it a bit clearer when set_raw_mode runs
  src/exec/use_pty/parent.rs
Labels: minor

#1025 Cleanup the exec module api a bit
  src/exec/interface.rs
  src/exec/mod.rs
  src/su/context.rs
  src/su/mod.rs
  src/sudo/env/tests.rs
  src/sudo/pipeline.rs
  src/system/mod.rs
Labels: C-exec

#1021 use CLOCK_BOOTTIME on FreeBSD
  src/system/mod.rs
  src/system/time.rs
  src/system/timestamp.rs
Labels: freebsd

#1029 Some changes to the exec module api
  src/common/context.rs
  src/exec/interface.rs
  src/exec/mod.rs
  src/exec/no_pty.rs
  src/exec/use_pty/parent.rs
  src/su/context.rs
  src/su/mod.rs
  src/sudo/pipeline.rs
Labels: C-exec

#1034 Changed Arch Linux install instructions.
  README.md
Labels: minor, external-packaging

#1037 Test on Fedora in CI
  .github/workflows/ci.yaml
Labels: CI, portability

#1027 Touchups and fixes for `--prompt` / `SUDO_PROMPT`
  docs/man/sudo.8.md
  src/pam/mod.rs
  src/sudo/pam.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_prompt.rs
Labels: minor

#1042 Fix title for sudoers.5 manpage
  docs/man/sudoers.5.md
Labels: documentation, minor

#1026 FreeBSD support is stable
  README.md
  src/sudo/mod.rs
Labels: freebsd

#1036 Make --validate aware of NOPASSWD
  src/sudo/pipeline.rs
  src/sudo/pipeline/list.rs
  src/sudoers/mod.rs
  src/sudoers/policy.rs
  test-framework/sudo-compliance-tests/src/sudo/nopasswd.rs
Labels: C-checker

#1052 Rewrite `.fold()` into something that is immediately readable
  src/sudoers/mod.rs
Labels: minor, ❤️+🦀

#1045 Prevent accidental lockouts
  src/visudo/mod.rs
Labels: C-visudo

#1049 Fix potential panic with misconfiguration
  docs/man/sudoers.5.md
  src/defaults/mod.rs
  src/sudoers/ast_names.rs
Labels: bug, C-parser
