Repository trifectatechfoundation/sudo-rs, pull requests merged in 2025-02, with the labels that each got.

#970 Couple of minor cleanups
  src/exec/event.rs
  src/exec/use_pty/parent.rs
  src/su/cli.rs
Labels: minor, C-exec

#982 Various pam changes
  src/common/error.rs
  src/pam/error.rs
  src/pam/mod.rs
  src/su/mod.rs
  src/sudo/pam.rs
Labels: C-pam

#988 Refactor "group_cmd_..." to use a peeking take while iterator.
  src/sudoers/mod.rs
Labels: minor

#993 Fix recursion-check in alias table
  src/sudoers/entry.rs
  src/sudoers/entry/verbose.rs
  src/sudoers/mod.rs
  src/sudoers/test/mod.rs
  src/sudoers/tokens.rs
Labels: C-parser

#992 Fix compliance test
  test-framework/sudo-compliance-tests/src/sudo/flag_user.rs
Labels: test-framework

#897 Specific Defaults
  src/defaults/settings_dsl.rs
  src/sudo/pipeline.rs
  src/sudo/pipeline/list.rs
  src/sudoers/ast.rs
  src/sudoers/ast_names.rs
  src/sudoers/mod.rs
  src/sudoers/policy.rs
  src/sudoers/test/mod.rs
  src/sudoers/tokens.rs
Labels: C-parser

#923 Add basic FreeBSD CI using Cirrus CI
  .cirrus.yml
Labels: CI, freebsd

#995 Make the compliance tests mostly pass on FreeBSD with og sudo too
  test-framework/e2e-tests/src/su/signal_handling/mod.rs
  test-framework/sudo-compliance-tests/src/helpers.rs
  test-framework/sudo-compliance-tests/src/su/limits.rs
  test-framework/sudo-compliance-tests/src/su/syslog.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_list/needs_auth.rs
  test-framework/sudo-compliance-tests/src/sudo/misc.rs
  test-framework/sudo-compliance-tests/src/sudo/nopasswd.rs
  test-framework/sudo-compliance-tests/src/sudo/pass_auth/stdin.rs
  test-framework/sudo-compliance-tests/src/sudo/passwd.rs
  test-framework/sudo-compliance-tests/src/sudo/password_retry.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/cmnd_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/env/keep.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/include.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/includedir.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/run_as.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/runas_alias.rs
  test-framework/sudo-compliance-tests/src/sudo/syslog.rs
  test-framework/sudo-compliance-tests/src/visudo/flag_file.rs
  test-framework/sudo-compliance-tests/src/visudo/what_now_prompt.rs
  test-framework/sudo-test/src/docker.rs
  test-framework/sudo-test/src/lib.rs
Labels: freebsd

#999 supply PAM file to make test work as intended
  test-framework/sudo-compliance-tests/src/sudo/limits.rs
Labels: minor

#966 SHELL canonicalization
  src/common/command.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_login.rs
  test-framework/sudo-compliance-tests/src/sudo/flag_shell.rs
Labels: non-compliant, test-framework

#997 Specific defaults compliance tests
  test-framework/sudo-compliance-tests/src/sudo/sudoers.rs
  test-framework/sudo-compliance-tests/src/sudo/sudoers/specific_defaults.rs
Labels: test-framework
