Repository trifectatechfoundation/sudo-rs, pull requests merged in 2025-06, with the labels that each got.

#1145 update README.md
  README.md
Labels: documentation

#1104 Add documentation for NOEXEC
  docs/man/sudoers.5.md
Labels: documentation, ubuntu

#1149 Further relax username requirements
  src/sudoers/test/mod.rs
  src/sudoers/tokens.rs
Labels: C-parser

#1158 Update the list of potentially relevant og-sudo advisories
  docs/sudo-cve.md
Labels: documentation, minor

#1160 Fix Typos in Documentation Comments
  src/sudoers/policy.rs
  src/sudoers/tokens.rs
Labels: minor

#1163 Fix typos in comments and documentation
  src/sudoers/entry.rs
  src/system/interface.rs
Labels: minor

#1166 Fix typos in comments
  src/exec/noexec.rs
  src/system/timestamp.rs
Labels: minor

#1168 Fix minor typo in README.md
  README.md
Labels: documentation, minor

#1172 Add 32-bit to the CI
  .github/workflows/ci.yaml
  src/pam/rpassword.rs
Labels: minor, CI, portability
